parserOptions:
  project: './tsconfig.json'

parser: '@typescript-eslint/parser'

plugins:
  - '@typescript-eslint'

extends:
  - ./index.js
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:@typescript-eslint/recommended-requiring-type-checking'
